# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('advertising.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]
 [  8.7  48.9  75. ]
 [ 57.5  32.8  23.5]
 [120.2  19.6  11.6]
 [  8.6   2.1   1. ]
 [199.8   2.6  21.2]
 [ 66.1   5.8  24.2]
 [214.7  24.    4. ]
 [ 23.8  35.1  65.9]
 [ 97.5   7.6   7.2]
 [204.1  32.9  46. ]
 [195.4  47.7  52.9]
 [ 67.8  36.6 114. ]
 [281.4  39.6  55.8]
 [ 69.2  20.5  18.3]
 [147.3  23.9  19.1]
 [218.4  27.7  53.4]
 [237.4   5.1  23.5]
 [ 13.2  15.9  49.6]
 [228.3  16.9  26.2]
 [ 62.3  12.6  18.3]
 [262.9   3.5  19.5]
 [142.9  29.3  12.6]
 [240.1  16.7  22.9]
 [248.8  27.1  22.9]
 [ 70.6  16.   40.8]
 [292.9  28.3  43.2]
 [112.9  17.4  38.6]
 [ 97.2   1.5  30. ]
 [265.6  20.    0.3]
 [ 95.7   1.4   7.4]
 [290.7   4.1   8.5]
 [266.9  43.8   5. ]
 [ 74.7  49.4  45.7]
 [ 43.1  26.7  35.1]
 [228.   37.7  32. ]
 [202.5  22.3  31.6]
 [177.   33.4  38.7]
 [293.6  27.7   1.8]
 [206.9   8.4  26.4]
 [ 25.1  25.7  43.3]
 [175.1  22.5  31.5]
 [ 89.7   9.9  35.7]
 [239.9  41.5

In [4]:
print(y)

[22.1 10.4 12.  16.5 17.9  7.2 11.8 13.2  4.8 15.6 12.6 17.4  9.2 13.7
 19.  22.4 12.5 24.4 11.3 14.6 18.  17.5  5.6 20.5  9.7 17.  15.  20.9
 18.9 10.5 21.4 11.9 13.2 17.4 11.9 17.8 25.4 14.7 10.1 21.5 16.6 17.1
 20.7 17.9  8.5 16.1 10.6 23.2 19.8  9.7 16.4 10.7 22.6 21.2 20.2 23.7
  5.5 13.2 23.8 18.4  8.1 24.2 20.7 14.  16.  11.3 11.  13.4 18.9 22.3
 18.3 12.4  8.8 11.  17.   8.7  6.9 14.2  5.3 11.  11.8 17.3 11.3 13.6
 21.7 20.2 12.  16.  12.9 16.7 14.   7.3 19.4 22.2 11.5 16.9 16.7 20.5
 25.4 17.2 16.7 23.8 19.8 19.7 20.7 15.   7.2 12.   5.3 19.8 18.4 21.8
 17.1 20.9 14.6 12.6 12.2  9.4 15.9  6.6 15.5  7.  16.6 15.2 19.7 10.6
  6.6 11.9 24.7  9.7  1.6 17.7  5.7 19.6 10.8 11.6  9.5 20.8  9.6 20.7
 10.9 19.2 20.1 10.4 12.3 10.3 18.2 25.4 10.9 10.1 16.1 11.6 16.6 16.
 20.6  3.2 15.3 10.1  7.3 12.9 16.4 13.3 19.9 18.  11.9 16.9  8.  17.2
 17.1 20.   8.4 17.5  7.6 16.7 16.5 27.  20.2 16.7 16.8 17.6 15.5 17.2
  8.7 26.2 17.6 22.6 10.3 17.3 20.9  6.7 10.8 11.9  5.9 19.6 17.3  7.6
 14.  1

## Encoding categorical data

In [0]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

In [5]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [7]:
print(X_train)

[[116.    7.7  23.1]
 [177.    9.3   6.4]
 [ 43.1  26.7  35.1]
 [ 62.3  12.6  18.3]
 [224.    2.4  15.6]
 [ 38.2   3.7  13.8]
 [ 70.6  16.   40.8]
 [147.3  23.9  19.1]
 [104.6   5.7  34.4]
 [ 76.3  27.5  16. ]
 [ 78.2  46.8  34.5]
 [168.4   7.1  12.8]
 [  8.7  48.9  75. ]
 [  7.8  38.9  50.6]
 [ 76.4   0.8  14.8]
 [129.4   5.7  31.3]
 [ 73.4  17.   12.9]
 [289.7  42.3  51.2]
 [ 19.6  20.1  17. ]
 [197.6   3.5   5.9]
 [284.3  10.6   6.4]
 [184.9  21.   22. ]
 [112.9  17.4  38.6]
 [ 23.8  35.1  65.9]
 [290.7   4.1   8.5]
 [ 19.4  16.   22.3]
 [293.6  27.7   1.8]
 [ 18.7  12.1  23.4]
 [134.3   4.9   9.3]
 [ 25.6  39.    9.3]
 [100.4   9.6   3.6]
 [ 80.2   0.    9.2]
 [188.4  18.1  25.6]
 [177.   33.4  38.7]
 [125.7  36.9  79.2]
 [209.6  20.6  10.7]
 [142.9  29.3  12.6]
 [184.9  43.9   1.7]
 [222.4   4.3  49.8]
 [241.7  38.   23.2]
 [ 17.2  45.9  69.3]
 [120.5  28.5  14.2]
 [ 89.7   9.9  35.7]
 [191.1  28.7  18.2]
 [ 75.5  10.8   6. ]
 [193.2  18.4  65.7]
 [ 85.7  35.8  49.3]
 [266.9  43.8

In [8]:
print(y_train)

[11.  14.8 10.1  9.7 16.6  7.6 10.5 14.6 10.4 12.  14.6 16.7  7.2  6.6
  9.4 11.  10.9 25.4  7.6 16.7 20.  20.5 11.9  9.2 17.8  6.6 20.7  6.7
 14.   9.5 10.7 11.9 19.9 17.1 15.9 20.9 15.  20.7 16.7 21.8 12.  14.2
 10.6 17.3 11.9 20.2 13.3 25.4 10.8 24.2  5.6 19.2 23.8 17.4 17.4 17.3
 12.9 11.8 20.9 15.5 17.9 13.2 20.1 10.3 19.8 12.3 12.6 20.7 17.1 18.2
  8.  22.1 25.5 16.  18.3 15.2 16.   8.5 18.  18.9 16.6  5.3  3.2 15.3
 17.  20.5 17.6 25.4 17.3 21.5 17.1 23.2 11.5 20.6 17.9  9.6 16.5 15.
 21.2 19.6 15.5 16.8 22.6  9.7 11.8 11.9 13.2 18.4  7.3 13.6 20.2 17.2
 16.7  4.8 13.7 18.4 17.5 17.7 24.4  8.8 27.  10.8 17.2 26.2 14.  20.2
 12.  16.4 14.  23.8 19.8 12.9 17.5 13.2 16.4  5.9  9.7 14.7 10.1 19.6
 10.4 22.6 10.1  1.6 11.6 19.7 17.2 12.2 16.  17.   7.  18.4 18.  20.9
 12.4  7.2 19.  19.4 17.6 19.8]


In [9]:
print(X_test)

[[163.3  31.6  52.9]
 [195.4  47.7  52.9]
 [292.9  28.3  43.2]
 [ 11.7  36.9  45.2]
 [220.3  49.    3.2]
 [ 75.1  35.   52.7]
 [216.8  43.9  27.2]
 [ 50.   11.6  18.4]
 [222.4   3.4  13.1]
 [175.1  22.5  31.5]
 [ 31.5  24.6   2.2]
 [ 56.2   5.7  29.7]
 [234.5   3.4  84.8]
 [  5.4  29.9   9.4]
 [139.5   2.1  26.6]
 [170.2   7.8  35.2]
 [  7.3  28.1  41.4]
 [197.6  23.3  14.2]
 [ 75.3  20.3  32.5]
 [237.4  27.5  11. ]
 [229.5  32.3  74.2]
 [ 67.8  36.6 114. ]
 [ 38.   40.3  11.9]
 [250.9  36.5  72.3]
 [ 69.    9.3   0.9]
 [ 53.5   2.   21.4]
 [213.5  43.   33.8]
 [139.3  14.5  10.2]
 [ 87.2  11.8  25.9]
 [  8.4  27.2   2.1]
 [199.8   2.6  21.2]
 [ 69.2  20.5  18.3]
 [198.9  49.4  60. ]
 [ 16.9  43.7  89.4]
 [280.7  13.9  37. ]
 [238.2  34.3   5.3]
 [ 48.3  47.    8.5]
 [273.7  28.9  59.7]
 [117.2  14.7   5.4]
 [ 27.5   1.6  20.7]]


In [10]:
print(y_test)

[16.9 22.4 21.4  7.3 24.7 12.6 22.3  8.4 16.5 16.1 11.   8.7 16.9  5.3
 10.3 16.7  5.5 16.6 11.3 18.9 19.7 12.5 10.9 22.2 11.3  8.1 21.7 13.4
 10.6  5.7 15.6 11.3 23.7  8.7 16.1 20.7 11.6 20.8 11.9  6.9]


## Training the Multiple Linear Regression model on the Training set

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [12]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[17.03 16.9 ]
 [20.41 22.4 ]
 [23.72 21.4 ]
 [ 9.27  7.3 ]
 [21.68 24.7 ]
 [12.57 12.6 ]
 [21.08 22.3 ]
 [ 8.69  8.4 ]
 [17.24 16.5 ]
 [16.67 16.1 ]
 [ 8.92 11.  ]
 [ 8.48  8.7 ]
 [18.21 16.9 ]
 [ 8.07  5.3 ]
 [12.65 10.3 ]
 [14.93 16.7 ]
 [ 8.13  5.5 ]
 [17.9  16.6 ]
 [11.01 11.3 ]
 [20.48 18.9 ]
 [20.81 19.7 ]
 [12.6  12.5 ]
 [10.91 10.9 ]
 [22.39 22.2 ]
 [ 9.42 11.3 ]
 [ 7.93  8.1 ]
 [20.84 21.7 ]
 [13.82 13.4 ]
 [10.77 10.6 ]
 [ 7.93  5.7 ]
 [15.96 15.6 ]
 [10.63 11.3 ]
 [20.8  23.7 ]
 [10.43  8.7 ]
 [21.58 16.1 ]
 [21.18 20.7 ]
 [12.13 11.6 ]
 [22.81 20.8 ]
 [12.61 11.9 ]
 [ 6.46  6.9 ]]


## Accuracy